-- Compatible with the original Hibernate schema. Existing installations explicitly
-- opt into baseline version 0 after backup; no existing table is replaced.
CREATE TABLE IF NOT EXISTS usuario (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome varchar(120) NOT NULL, email varchar(180) NOT NULL UNIQUE,
 senha_hash varchar(255) NOT NULL, tipo varchar(30) NOT NULL, ativo boolean NOT NULL DEFAULT true
);
CREATE TABLE IF NOT EXISTS unidade_atendimento (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nome varchar(150) NOT NULL, endereco varchar(255) NOT NULL, telefone varchar(20),
 ocupacao_atual integer NOT NULL DEFAULT 0, latitude double precision, longitude double precision,
 ultima_atualizacao timestamp NOT NULL, tipo varchar(255) NOT NULL, capacidade_area_monitorada integer NOT NULL
);
CREATE TABLE IF NOT EXISTS dispositivo_camera (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, nome varchar(255) NOT NULL,
 chave_api varchar(255) NOT NULL UNIQUE, unidade_atendimento_id bigint NOT NULL REFERENCES unidade_atendimento(id),
 ativo boolean NOT NULL DEFAULT true, ultima_comunicacao timestamp
);
CREATE TABLE IF NOT EXISTS historico_ocupacao (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 unidade_atendimento_id bigint NOT NULL REFERENCES unidade_atendimento(id),
 quantidade_pessoas integer NOT NULL, percentual_ocupacao double precision NOT NULL,
 registrado_em timestamp NOT NULL, registrado_por bigint REFERENCES usuario(id), origem varchar(255)
);
CREATE TABLE IF NOT EXISTS avaliacao (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 nota integer NOT NULL, comentario varchar(500), criado_em timestamp NOT NULL,
 unidade_atendimento_id bigint NOT NULL REFERENCES unidade_atendimento(id), usuario_id bigint REFERENCES usuario(id)
);
CREATE TABLE IF NOT EXISTS favorito (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 usuario_id bigint NOT NULL REFERENCES usuario(id), unidade_id bigint NOT NULL REFERENCES unidade_atendimento(id),
 CONSTRAINT uk_favorito_usuario_unidade UNIQUE(usuario_id,unidade_id)
);

