ALTER TABLE usuario ADD COLUMN IF NOT EXISTS auth_version bigint NOT NULL DEFAULT 0;
ALTER TABLE dispositivo_camera ADD COLUMN IF NOT EXISTS chave_hash varchar(64);
ALTER TABLE dispositivo_camera ADD COLUMN IF NOT EXISTS chave_revogada_em timestamp with time zone;
ALTER TABLE dispositivo_camera ADD COLUMN IF NOT EXISTS chave_gerada_em timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dispositivo_camera ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dispositivo_camera ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE dispositivo_camera ADD COLUMN IF NOT EXISTS version bigint NOT NULL DEFAULT 0;
ALTER TABLE historico_ocupacao ADD COLUMN IF NOT EXISTS dispositivo_id bigint REFERENCES dispositivo_camera(id) ON DELETE SET NULL;
CREATE TABLE desafio_recuperacao (
 usuario_id bigint PRIMARY KEY REFERENCES usuario(id),
 codigo_hash varchar(64) NOT NULL, expira_em timestamp with time zone NOT NULL,
 solicitado_em timestamp with time zone NOT NULL, janela_inicio timestamp with time zone NOT NULL,
 solicitacoes integer NOT NULL, tentativas integer NOT NULL, consumido_em timestamp with time zone
);
CREATE TABLE solicitacao_suporte (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 usuario_id bigint NOT NULL REFERENCES usuario(id), assunto varchar(150) NOT NULL,
 categoria varchar(40) NOT NULL, descricao varchar(5000) NOT NULL,
 status varchar(30) NOT NULL, created_at timestamp with time zone NOT NULL,
 updated_at timestamp with time zone NOT NULL, version bigint NOT NULL DEFAULT 0
);
CREATE INDEX idx_historico_unidade_origem_data ON historico_ocupacao(unidade_atendimento_id,origem,registrado_em DESC);
CREATE INDEX idx_avaliacao_unidade_data ON avaliacao(unidade_atendimento_id,criado_em DESC);
CREATE INDEX idx_avaliacao_usuario_data ON avaliacao(usuario_id,criado_em DESC);
CREATE INDEX idx_camera_unidade ON dispositivo_camera(unidade_atendimento_id);
CREATE INDEX idx_suporte_usuario_data ON solicitacao_suporte(usuario_id,created_at DESC);
CREATE INDEX idx_suporte_status_categoria_data ON solicitacao_suporte(status,categoria,created_at DESC);

